// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlaYnanh-74tSKfOtL2mUZIOoSN5A4kGU',
    appId: '1:576669009925:web:6a6088c45875b8a601b46c',
    messagingSenderId: '576669009925',
    projectId: 'muzahirfyp',
    authDomain: 'muzahirfyp.firebaseapp.com',
    storageBucket: 'muzahirfyp.appspot.com',
    measurementId: 'G-NT2NM2QTX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLzJ9X0ghZz2kAbiofs3QLYbz_thcPuhk',
    appId: '1:576669009925:android:004361db5232ddca01b46c',
    messagingSenderId: '576669009925',
    projectId: 'muzahirfyp',
    storageBucket: 'muzahirfyp.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlaYnanh-74tSKfOtL2mUZIOoSN5A4kGU',
    appId: '1:576669009925:web:3706304548dcd76b01b46c',
    messagingSenderId: '576669009925',
    projectId: 'muzahirfyp',
    authDomain: 'muzahirfyp.firebaseapp.com',
    storageBucket: 'muzahirfyp.appspot.com',
    measurementId: 'G-BTP6ZEX12H',
  );
}
